/** @format */

export const subscriptions = [
  {
    key: 1,
    hostName: 'Floyd Miles',
    postcode: 'B4 7DA',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '05',
    activeSince: '22 June 2023',
    successfulDeliveries: '08',
    nextDelivery: '22 June 2023',
  },
  {
    key: 2,
    hostName: 'Brooklyn Simmons',
    postcode: 'SW2 5JD',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '09',
    activeSince: '22 June 2023',
    successfulDeliveries: '09',
    nextDelivery: '22 June 2023',
  },
  {
    key: 3,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 4,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 5,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 6,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 7,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 8,
    hostName: 'Floyd Miles',
    postcode: 'B4 7DA',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '05',
    activeSince: '22 June 2023',
    successfulDeliveries: '08',
    nextDelivery: '22 June 2023',
  },
  {
    key: 9,
    hostName: 'Brooklyn Simmons',
    postcode: 'SW2 5JD',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '09',
    activeSince: '22 June 2023',
    successfulDeliveries: '09',
    nextDelivery: '22 June 2023',
  },
  {
    key: 10,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 11,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 12,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 13,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 14,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 15,
    hostName: 'Floyd Miles',
    postcode: 'B4 7DA',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '05',
    activeSince: '22 June 2023',
    successfulDeliveries: '08',
    nextDelivery: '22 June 2023',
  },
  {
    key: 16,
    hostName: 'Brooklyn Simmons',
    postcode: 'SW2 5JD',
    subscriptionValue: 240,
    frequency: '2 Weeks',
    members: '09',
    activeSince: '22 June 2023',
    successfulDeliveries: '09',
    nextDelivery: '22 June 2023',
  },
  {
    key: 17,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 18,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
  {
    key: 19,
    hostName: 'Cody Fisher',
    postcode: 'S1 2HE',
    subscriptionValue: 240,
    frequency: 'Monthly',
    members: '02',
    activeSince: '22 June 2023',
    successfulDeliveries: '12',
    nextDelivery: '22 June 2023',
  },
  {
    key: 20,
    hostName: 'Kathryn Murphy',
    postcode: 'BD1 2RD',
    subscriptionValue: 240,
    frequency: ' 2 Months',
    members: '04',
    activeSince: '22 June 2023',
    successfulDeliveries: '01',
    nextDelivery: '22 June 2023',
  },
];

export const pendingLateCompletedOrders = [
  {
    key: 21,
    orderId: 'ORD-1562792779615',
    hostName: 'Floyd Miles',
    producerName: 'Flying Horse Coffee',
    postcode: 'BD1 2RD',
    address: '123 Main Street',
    category: 'Tea & Coffee',
    orderValue: 240,
    expectedDelivery: '2022-12-01',
    orderStatus: 'Pending',
  },
  {
    key: 22,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 23,
    orderId: 'ORD-1562792779615',
    hostName: 'Cody Fisher',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 24,
    orderId: 'ORD-1562792779615',
    hostName: 'Kathryn Murphy',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 25,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 26,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 27,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 28,
    orderId: 'ORD-1562792779615',
    hostName: 'Floyd Miles',
    producerName: 'Flying Horse Coffee',
    postcode: 'BD1 2RD',
    address: '123 Main Street',
    category: 'Tea & Coffee',
    orderValue: 240,
    expectedDelivery: '2022-12-01',
    orderStatus: 'Pending',
  },
  {
    key: 29,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 30,
    orderId: 'ORD-1562792779615',
    hostName: 'Cody Fisher',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 31,
    orderId: 'ORD-1562792779615',
    hostName: 'Kathryn Murphy',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 32,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 33,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Pending',
  },
  {
    key: 34,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Delivered',
  },
  {
    key: 35,
    orderId: 'ORD-1562792779615',
    hostName: 'Floyd Miles',
    producerName: 'Flying Horse Coffee',
    postcode: 'BD1 2RD',
    address: '123 Main Street',
    category: 'Tea & Coffee',
    orderValue: 240,
    expectedDelivery: '2022-12-01',
    orderStatus: 'Delivered',
  },
  {
    key: 36,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Delivered',
  },
  {
    key: 37,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Delivered',
  },
  {
    key: 38,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Delivered',
  },
  {
    key: 39,
    orderId: 'ORD-1562792779615',
    hostName: 'Floyd Miles',
    producerName: 'Flying Horse Coffee',
    postcode: 'BD1 2RD',
    address: '123 Main Street',
    category: 'Tea & Coffee',
    orderValue: 240,
    expectedDelivery: '2022-12-01',
    orderStatus: 'Late',
  },
  {
    key: 40,
    orderId: 'ORD-1562792779615',
    hostName: 'Brooklyn Simmons',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Late',
  },
  {
    key: 41,
    orderId: 'ORD-1562792779615',
    hostName: 'Cody Fisher',
    producerName: 'Cacklebean Eggs',
    postcode: 'SW2 5JD',
    address: '456 Oak Avenue',
    category: 'Farm & Dairy',
    orderValue: 240,
    expectedDelivery: '2022-12-10',
    orderStatus: 'Late',
  },
];

export const invoiceItems = [
  {
    key: 241,
    productCode: '29128',
    productName: 'AA DENAVOLO, "CATAVELA" BIANCO"',
    price: 2,
    quantity: 5,
    totalPrice: 10,
  },
  {
    key: 242,
    productCode: '20932',
    productName: 'Product name',
    price: 2,
    quantity: 5,
    totalPrice: 10,
  },
];
